endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  host:
      connect-timeout-millis: 5000
      socket-timeout-millis: 10000

  ignoredServices: "*"
  routes:
    productcomposite:
      path: /productcomposite/**
      serviceId: productcomposite

#hystrix:
#    command:
#        default:
#            execution:
#                isolation:
#                    thread:
#                        timeoutInMilliseconds: 10000

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

